apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-release-web
  namespace: dev-cmdb
  labels:
    app: dev-release-web
spec:
  selector:
    matchLabels:
      name: dev-release-web
  replicas: 2
  template:
    metadata:
      labels:
        name: dev-release-web
        app-version: "<VERSION>"
    spec:
      # securityContext:
      #   runAsUser: 472
      #   fsGroup: 472
      containers:
        - name: dev-release-web
          image: devops-registry-vpc.cn-shanghai.cr.aliyuncs.com/ipfsforce/devops/release-frontend:<VERSION>
          ports:
            - containerPort: 80
              name: release-web
          volumeMounts:
            - name: config-json
              mountPath: /opt/dist/config.json
              subPath: config.json
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-json
          configMap:
            name: app-release-frontend-config-json
        - name: nginx-conf
          configMap:
            name: app-release-frontend-nginx-conf
---
kind: Service
apiVersion: v1
metadata:
  name: dev-release-web
  namespace: dev-cmdb
spec:
  selector:
    name: dev-release-web
  ports:
    - port: 80
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-release-web
  namespace: dev-cmdb
  annotations:
spec:
  rules:
    - host: dev-release.ops.ipfsyuanli.com
      http:
        paths:
          - path: /
            backend:
              serviceName: dev-release-web
              servicePort: 80
